# Generated by Django 5.0.6 on 2026-08-14 03:44

import django.db.models.deletion
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_institution_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_item_id', models.CharField(max_length=64, unique=True)),
                ('access_token', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('status', models.CharField(choices=[('active', 'Active'), ('login_required', 'Re-authentication required'), ('error', 'Error')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.institution')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_items', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_account_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('mask', models.CharField(blank=True, max_length=8)),
                ('account_type', models.CharField(blank=True, max_length=32)),
                ('account_subtype', models.CharField(blank=True, max_length=32)),
                ('plaid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='banking.plaiditem')),
            ],
        ),
    ]
